/**
 * The host's own record of what a delegation changed ([[REQ-340]], DOC-60 §1).
 *
 * WHY IT EXISTS. Everything else on a delegation result is the worker's word:
 * the `delegate` operation declares `provenance: "untrusted"`, so a worker that
 * reports nothing leaves nothing behind and a worker that reports wrongly is
 * not contradicted. Two of the seven delegations that had ever run came back
 * `outcome: silent` with real element writes committed on the site, and the
 * only recovery was to re-inspect the site at the consultant's rate — which is
 * the cost delegation exists to remove.
 *
 * SO THE HOST LOOKS FOR ITSELF. A capture of the draft is taken before the
 * worker is briefed and another after its work ends, and the difference between
 * them is derived here. No part of it comes from anything the worker says.
 *
 * STATE, NOT A LOG OF WRITES. The change journal is beside this and is
 * deliberately not its source, for the two reasons DOC-60 gives. An element
 * address is regenerated by every write, so a path-keyed per-write record can
 * misalign against a tree that has moved under it; and a journal record holds a
 * TEXT rendering of before and after, which was byte-identical on 276 of the
 * 337 `l1.set` records on the real log — because padding, colour, font size and
 * layout are most of what a worker changes and none of them change an element's
 * words. Comparing two states has neither failure: an address is read off the
 * tree it belongs to, and a difference is a difference whatever it is in.
 *
 * IT SPEAKS FOR A WINDOW AND ATTRIBUTES NOTHING. Anything that writes to the
 * draft between the two captures appears here, whoever wrote it. The delegating
 * session is blocked awaiting its worker, so the only other writer is a second
 * session or the page editor — rare, and stated rather than hidden, because a
 * reader who mistook this for an attribution would be reading a claim it never
 * makes. The surface prose says the same thing where the field is described.
 *
 * WHAT IT COSTS. Both captures and the comparison are host-side and add no
 * tokens; only the difference list enters the conversation, and it is a list of
 * what CHANGED rather than of what is there. One element write measured 287
 * bytes against a 2,582-byte element. {@link DIFFERENCE_BUDGET} bounds the
 * pathological case out loud rather than quietly.
 */

import { formatL1Path } from '@1stcontact/site-schema'
import type { L1Node } from '@1stcontact/site-schema'
import { canonicalJson, diffOutlines } from '../../store/revision-model'
import type { SiteOutline } from '../../store/revision-model'
import type { SiteStore, StoredPage } from '../../store/site-store'

// ── what a capture is ────────────────────────────────────────────────────────

/**
 * The draft as the store holds it at one moment, plus where the change counter
 * stood ([[REQ-340]]).
 *
 * THE OUTLINE IS THE STORE'S OWN SHAPE and not a second one: `site.json`, every
 * page, and every asset STAMPED rather than carried, which is what lets a
 * capture read no asset bytes at all.
 *
 * THE STAMP IS THE CONTENT DIGEST, so the capture is assembled from
 * `assetManifest` rather than taken whole from `draftOutline`. An outline's own
 * stamp is documented as opaque and comparable only against another from the
 * same store — the file and memory tiers use the byte length — which is enough
 * to decide *did this asset move* and is not something to put in front of a
 * model as a value. `assetManifest` answers with a real SHA-256 on every
 * adapter and still reads no bytes, so this is the same construction
 * `snapshotEntries` already makes for a revision.
 *
 * THE COUNTER IS THE BRACKET. It is what the framework's `account.from` and
 * `account.to` carry, and it is the whole reason the record is checkable rather
 * than asserted: a caller that doubts the difference list reads `list_changes`
 * between the same two numbers and derives it again, for two integers' worth of
 * payload.
 */
export interface DraftCapture {
  /** The draft's change count when the capture was taken. */
  at: number
  outline: SiteOutline
}

/** Take one ([[REQ-340]]). */
export async function captureDraft(store: SiteStore, site: string): Promise<DraftCapture> {
  const [at, siteJson, pages, assets] = await Promise.all([
    store.counter(site),
    store.readSiteJson(site),
    store.readPages(site),
    store.assetManifest(site),
  ])
  return {
    at,
    outline: { siteJson, pages, assets: assets.map(({ name, digest }) => ({ name, stamp: digest })) },
  }
}

// ── what a difference is ─────────────────────────────────────────────────────

/**
 * One difference between two captures ([[REQ-340]] behaviour 2).
 *
 * WHERE IT IS, in exactly one of three vocabularies, and which one is readable
 * off which locators are present:
 *
 *   - `page` and `address` — a field of one element on one page. `module` and
 *     `slot` come with the address when the element sits inside a component
 *     instance, because that is the scope the write operation takes and an
 *     address without it reaches somewhere else.
 *   - `page` alone — a field of the page's own definition: its title, its
 *     slug, its search-and-share wording, a module's configuration.
 *   - `asset` — one file under the draft's assets, compared on the store's own
 *     content identity.
 *   - none of them — a field of `site.json`.
 *
 * `field` is the dotted path WITHIN whatever the locators named, and `''` means
 * the thing itself: an element that was added or removed has no field that
 * changed, it is the change.
 *
 * ABSENT IS NOT NULL. A field that did not exist before carries no `before` at
 * all, and one that no longer exists carries no `after` — rather than either
 * being reported as a change from or to nothing, which are different facts and
 * would otherwise be indistinguishable from a field whose value IS null.
 *
 * WHICH TREE AN ADDRESS BELONGS TO follows from the same rule. An entry with no
 * `after` names what was removed, so its address is the one it had in the
 * before-capture; every other address is the one it has now, which is the one
 * the caller can act on.
 */
export interface DraftDifference {
  /** The page's own id, when the difference is on a page. */
  page?: string
  /** The element's dotted address, when the difference is inside an L1 tree. */
  address?: string
  /** The component instance the address is scoped to, when it is inside one. */
  module?: string
  slot?: string
  /** The asset's name, when the difference is an asset. */
  asset?: string
  /** The dotted path within what the locators named. `''` is the thing itself. */
  field: string
  /** Absent when what is described did not exist before. */
  before?: unknown
  /** Absent when what is described no longer exists. */
  after?: unknown
}

/**
 * The whole record: what differs, and whether anything was left out.
 *
 * AN EMPTY LIST IS AN ANSWER ([[REQ-340]] behaviour 3). A delegation that
 * changed nothing yields `differences: []`, which is not the same fact as no
 * record at all — the framework omits `account` entirely when no capture was
 * taken, so "nothing changed" and "nobody looked" are distinguishable without
 * either having to be spelled.
 */
export interface DraftChanges {
  differences: DraftDifference[]
  /**
   * How many further differences there were, present only when the budget bit.
   *
   * A COUNT RATHER THAN A SILENT CUT. A truncated list that says so is still
   * evidence — it tells the caller to go and look — where one that does not is
   * a false statement about the site.
   */
  truncated?: number
}

/**
 * How much of the conversation a difference list may take, in serialised
 * characters and in entries.
 *
 * A DELEGATION'S DIFFERENCE IS SMALL AND THESE ARE NOT ITS SIZE. They bound the
 * case this cannot otherwise bound: a whole page added or removed inside the
 * window carries its whole definition, honestly, because that IS the change —
 * and thirty of them would carry the site. The budget is generous enough that
 * an ordinary run never meets it and low enough that meeting it costs a
 * paragraph rather than a turn.
 */
export const DIFFERENCE_BUDGET = 24_000
export const DIFFERENCE_LIMIT = 200

/**
 * The most cells a sibling alignment will fill before falling back to comparing
 * by position.
 *
 * The alignment is quadratic and L1 bounds a document at 2,000 nodes, so the
 * worst case is real even though nothing has ever come near it. Past this the
 * comparison is still correct — it just reports an insertion the way a
 * position-wise walk does, as a run of differences rather than as one addition.
 */
const ALIGNMENT_CELLS = 250_000

// ── the comparison ───────────────────────────────────────────────────────────

/**
 * What changed between two captures ([[REQ-340]]).
 *
 * THE CHEAP QUESTION FIRST. `diffOutlines` already answers *which paths differ*
 * — the same comparison `1c status` and the per-turn digest read — so the
 * expensive descent happens only into the pages that actually moved. A worker
 * that touched one element on one page of forty costs one page's walk.
 */
export function draftChanges(before: DraftCapture, after: DraftCapture): DraftChanges {
  const differences: DraftDifference[] = []
  let truncated = 0
  let spent = 0
  const emit = (difference: DraftDifference): void => {
    if (truncated > 0 || differences.length >= DIFFERENCE_LIMIT) {
      truncated += 1
      return
    }
    spent += canonicalJson(difference).length
    if (spent > DIFFERENCE_BUDGET && differences.length > 0) {
      truncated += 1
      return
    }
    differences.push(difference)
  }

  const paths = diffOutlines(before.outline, after.outline)
  const changed = new Set([...paths.added, ...paths.modified, ...paths.removed])

  if (changed.has('site.json')) {
    diffValue(before.outline.siteJson, after.outline.siteJson, '', {}, emit)
  }

  const beforePages = byName(before.outline.pages)
  const afterPages = byName(after.outline.pages)
  for (const path of [...changed].sort()) {
    if (!path.startsWith('pages/')) continue
    const name = path.slice('pages/'.length)
    diffPage(name, beforePages.get(name), afterPages.get(name), emit)
  }

  const beforeAssets = new Map(before.outline.assets.map((a) => [a.name, a.stamp]))
  const afterAssets = new Map(after.outline.assets.map((a) => [a.name, a.stamp]))
  for (const path of [...changed].sort()) {
    if (!path.startsWith('assets/')) continue
    const name = path.slice('assets/'.length)
    emit({
      asset: name,
      field: '',
      ...(beforeAssets.has(name) ? { before: beforeAssets.get(name) } : {}),
      ...(afterAssets.has(name) ? { after: afterAssets.get(name) } : {}),
    })
  }

  return truncated > 0 ? { differences, truncated } : { differences }
}

/** Every page by the key the store calls it, e.g. `home.json`. */
function byName(pages: readonly StoredPage[]): Map<string, Record<string, unknown>> {
  return new Map(pages.map(({ name, page }) => [name, page]))
}

/**
 * A page's id — what an address is scoped to and what the model calls it.
 *
 * Read off the definition, and the store's key only when the definition holds
 * none: the key is `home.json`, which is what the page is CALLED in storage,
 * and every operation on the surface takes `home`.
 */
function pageIdOf(name: string, page: Record<string, unknown> | undefined): string {
  const id = page?.id
  return typeof id === 'string' && id.length > 0 ? id : name.replace(/\.json$/, '')
}

/**
 * The two halves of a page definition, compared each in its own vocabulary.
 *
 * `l1` and `modules` hold element trees and are walked as trees, so a
 * difference inside one carries the address a write takes. Everything else is
 * the page's own definition and is compared as a plain structure.
 */
function diffPage(
  name: string,
  before: Record<string, unknown> | undefined,
  after: Record<string, unknown> | undefined,
  emit: (difference: DraftDifference) => void,
): void {
  const page = pageIdOf(name, after ?? before)
  if (before === undefined || after === undefined) {
    emit({
      page,
      field: '',
      ...(before === undefined ? {} : { before }),
      ...(after === undefined ? {} : { after }),
    })
    return
  }

  for (const key of unionKeys(before, after)) {
    if (key === 'l1' || key === 'modules') continue
    diffValue(before[key], after[key], key, { page }, emit)
  }

  const beforeRoot = rootOf(before)
  const afterRoot = rootOf(after)
  if (beforeRoot !== null && afterRoot !== null) {
    diffNodes([beforeRoot], [afterRoot], { page }, [], [], emit)
  } else if (beforeRoot !== null || afterRoot !== null) {
    diffValue(before.l1, after.l1, 'l1', { page }, emit)
  }

  diffModules(before, after, page, emit)
}

/** A page's own L1 root, or null when it holds none. */
function rootOf(page: Record<string, unknown>): L1Node | null {
  const root = (page.l1 as { root?: L1Node } | undefined)?.root
  return root ?? null
}

/**
 * Component instances, matched by their id rather than by position.
 *
 * An instance's id is stable across a write — that is what makes it an id — so
 * matching on it means reordering the list reports the reorder and nothing
 * else, where a position-wise comparison would report every instance past the
 * first as wholly replaced.
 */
function diffModules(
  before: Record<string, unknown>,
  after: Record<string, unknown>,
  page: string,
  emit: (difference: DraftDifference) => void,
): void {
  const beforeModules = modulesById(before)
  const afterModules = modulesById(after)
  for (const id of [...new Set([...beforeModules.keys(), ...afterModules.keys()])].sort()) {
    const b = beforeModules.get(id)
    const a = afterModules.get(id)
    if (b === undefined || a === undefined) {
      emit({
        page,
        module: id,
        field: '',
        ...(b === undefined ? {} : { before: b }),
        ...(a === undefined ? {} : { after: a }),
      })
      continue
    }
    for (const key of unionKeys(b, a)) {
      if (key === 'slots') continue
      diffValue(b[key], a[key], key, { page, module: id }, emit)
    }
    const beforeSlots = (b.slots ?? {}) as Record<string, unknown>
    const afterSlots = (a.slots ?? {}) as Record<string, unknown>
    for (const slot of [...new Set([...Object.keys(beforeSlots), ...Object.keys(afterSlots)])].sort()) {
      const bs = beforeSlots[slot]
      const as = afterSlots[slot]
      if (bs === undefined || as === undefined) {
        diffValue(bs, as, '', { page, module: id, slot }, emit)
        continue
      }
      diffNodes(slotRoots(bs), slotRoots(as), { page, module: id, slot }, [], [], emit)
    }
  }
}

/** Every instance by id, skipping anything that carries none to match on. */
function modulesById(page: Record<string, unknown>): Map<string, Record<string, unknown>> {
  const out = new Map<string, Record<string, unknown>>()
  const modules = Array.isArray(page.modules) ? (page.modules as Record<string, unknown>[]) : []
  for (const instance of modules) {
    const id = instance?.id
    if (typeof id === 'string' && id.length > 0) out.set(id, instance)
  }
  return out
}

/** A slot holds one node or a list of them; both address as a root list. */
function slotRoots(value: unknown): L1Node[] {
  return Array.isArray(value) ? (value as L1Node[]) : [value as L1Node]
}

// ── the element tree ─────────────────────────────────────────────────────────

/** Which page, element and component scope a difference is being reported in. */
interface Where {
  page?: string
  module?: string
  slot?: string
}

/**
 * Compare two sibling lists of elements, then descend ([[REQ-340]] behaviour 7).
 *
 * SIBLINGS ARE ALIGNED, NOT INDEXED. A worker that inserts a band at the top of
 * a page has changed one thing, and a position-wise walk would report every
 * band behind it as rewritten — a page's worth of difference for a page's worth
 * of nothing, which is exactly the cost this record exists not to have. The
 * alignment finds the cheapest correspondence between the two lists, so an
 * insertion is one addition and the siblings it displaced are unchanged.
 *
 * THE COST FUNCTION IS THE WHOLE OF THE JUDGEMENT. Identical nodes cost
 * nothing, so an untouched sibling always matches itself. Two nodes of the same
 * kind cost one — cheaper than removing one and adding the other — so an edited
 * heading is reported as the field that changed in it. Two nodes of different
 * kinds cost more than the pair of operations that would replace one with the
 * other, so a text run that became an image is an addition and a removal rather
 * than a heap of field differences between things that share no fields.
 */
function diffNodes(
  before: readonly L1Node[],
  after: readonly L1Node[],
  where: Where,
  beforePrefix: readonly number[],
  afterPrefix: readonly number[],
  emit: (difference: DraftDifference) => void,
): void {
  for (const step of align(before, after, nodeCost)) {
    if (step.before === undefined) {
      emit({
        ...where,
        address: formatL1Path([...afterPrefix, step.after as number]),
        field: '',
        after: after[step.after as number],
      })
      continue
    }
    if (step.after === undefined) {
      emit({
        ...where,
        address: formatL1Path([...beforePrefix, step.before]),
        field: '',
        before: before[step.before],
      })
      continue
    }
    const b = before[step.before] as unknown as Record<string, unknown>
    const a = after[step.after] as unknown as Record<string, unknown>
    if (same(b, a)) continue
    const at = [...afterPrefix, step.after]
    const address = formatL1Path(at)
    for (const key of unionKeys(b, a)) {
      if (key === 'children') continue
      diffValue(b[key], a[key], key, { ...where, address }, emit)
    }
    const beforeChildren = childrenOf(b)
    const afterChildren = childrenOf(a)
    if (beforeChildren.length > 0 || afterChildren.length > 0) {
      diffNodes(beforeChildren, afterChildren, where, [...beforePrefix, step.before], at, emit)
    }
  }
}

function childrenOf(node: Record<string, unknown>): L1Node[] {
  return Array.isArray(node.children) ? (node.children as L1Node[]) : []
}

/** See {@link diffNodes} — the judgement the alignment is made of. */
function nodeCost(b: L1Node, a: L1Node): number {
  if (same(b, a)) return 0
  return (b as { kind?: string }).kind === (a as { kind?: string }).kind ? 1 : 3
}

// ── the structure below an element ───────────────────────────────────────────

/**
 * Compare two values and report the fields that differ ([[REQ-340]] behaviour 2).
 *
 * IT DESCENDS ONLY WHERE BOTH SIDES ARE THE SAME SHAPE. Two objects are
 * compared key by key and two lists are aligned; anything else — a value that
 * became an object, an object that became absent — is reported whole at the
 * path it sits at, because there is no smaller true statement to make about it.
 *
 * LISTS USE THE SAME ALIGNMENT THE ELEMENT TREE USES, for the same reason and
 * over the same algorithm: a run inserted into a paragraph is one addition, not
 * a rewrite of every run behind it.
 */
function diffValue(
  before: unknown,
  after: unknown,
  field: string,
  where: Where & { address?: string },
  emit: (difference: DraftDifference) => void,
): void {
  if (same(before, after)) return

  if (isPlainObject(before) && isPlainObject(after)) {
    for (const key of unionKeys(before, after)) {
      diffValue(before[key], after[key], join(field, key), where, emit)
    }
    return
  }

  if (Array.isArray(before) && Array.isArray(after)) {
    for (const step of align(before, after, (b, a) => (same(b, a) ? 0 : 1))) {
      if (step.before === undefined) {
        emit({ ...where, field: join(field, String(step.after)), after: after[step.after as number] })
      } else if (step.after === undefined) {
        emit({ ...where, field: join(field, String(step.before)), before: before[step.before] })
      } else {
        diffValue(before[step.before], after[step.after], join(field, String(step.after)), where, emit)
      }
    }
    return
  }

  emit({
    ...where,
    field,
    ...(before === undefined ? {} : { before }),
    ...(after === undefined ? {} : { after }),
  })
}

/**
 * Equality on the DEFINITION rather than on the serialisation, with absence
 * kept distinct from null.
 *
 * `canonicalJson` renders `undefined` as `null` — correct where it is used, a
 * store comparing two definitions neither of which can hold an `undefined` —
 * and wrong here, where a field arriving for the first time is precisely the
 * case behaviour 2 asks to be reported as newly present.
 */
function same(before: unknown, after: unknown): boolean {
  if (before === undefined || after === undefined) return before === after
  return canonicalJson(before) === canonicalJson(after)
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function unionKeys(
  before: Record<string, unknown>,
  after: Record<string, unknown>,
): string[] {
  return [...new Set([...Object.keys(before), ...Object.keys(after)])].sort()
}

function join(field: string, key: string): string {
  return field === '' ? key : `${field}.${key}`
}

// ── the alignment ────────────────────────────────────────────────────────────

/** One correspondence: a matched pair, an addition, or a removal. */
interface AlignStep {
  before?: number
  after?: number
}

/**
 * The cheapest correspondence between two lists, given what a substitution
 * costs ([[REQ-340]]).
 *
 * ONE ALGORITHM, TWO CONSUMERS — the element tree and every list below an
 * element — because they are asking the same question and an insertion has to
 * cost the same in both. Adding and removing each cost one, so a substitution
 * priced above two is a pair of operations instead, which is how a caller
 * states *these are not versions of each other*.
 *
 * PAST {@link ALIGNMENT_CELLS} IT COMPARES BY POSITION, which is the honest
 * degradation: still correct, just no longer able to see an insertion as one.
 */
function align<T>(
  before: readonly T[],
  after: readonly T[],
  cost: (before: T, after: T) => number,
): AlignStep[] {
  const n = before.length
  const m = after.length
  if (n === 0) return after.map((_, index) => ({ after: index }))
  if (m === 0) return before.map((_, index) => ({ before: index }))
  if (n * m > ALIGNMENT_CELLS) return positionwise(n, m)

  const width = m + 1
  const table = new Float64Array((n + 1) * width)
  for (let i = 1; i <= n; i += 1) table[i * width] = i
  for (let j = 1; j <= m; j += 1) table[j] = j
  for (let i = 1; i <= n; i += 1) {
    for (let j = 1; j <= m; j += 1) {
      const substitute = table[(i - 1) * width + (j - 1)] + cost(before[i - 1], after[j - 1])
      const remove = table[(i - 1) * width + j] + 1
      const add = table[i * width + (j - 1)] + 1
      table[i * width + j] = Math.min(substitute, remove, add)
    }
  }

  const steps: AlignStep[] = []
  let i = n
  let j = m
  while (i > 0 || j > 0) {
    if (i > 0 && j > 0) {
      const substitute = table[(i - 1) * width + (j - 1)] + cost(before[i - 1], after[j - 1])
      if (table[i * width + j] === substitute) {
        steps.push({ before: i - 1, after: j - 1 })
        i -= 1
        j -= 1
        continue
      }
    }
    // Additions before removals at equal cost, so a replacement reads as the new
    // thing arriving where the old one was rather than as a gap that is filled
    // several entries later.
    if (j > 0 && table[i * width + j] === table[i * width + (j - 1)] + 1) {
      steps.push({ after: j - 1 })
      j -= 1
      continue
    }
    steps.push({ before: i - 1 })
    i -= 1
  }
  return steps.reverse()
}

/** The fallback: pair by index, and report the tail as added or removed. */
function positionwise(n: number, m: number): AlignStep[] {
  const steps: AlignStep[] = []
  const shared = Math.min(n, m)
  for (let k = 0; k < shared; k += 1) steps.push({ before: k, after: k })
  for (let k = shared; k < m; k += 1) steps.push({ after: k })
  for (let k = shared; k < n; k += 1) steps.push({ before: k })
  return steps
}

// ── what the worker did, when it did not say ─────────────────────────────────

/** The AI library, which is JavaScript and has no types to import. */
type Untyped = any // eslint-disable-line @typescript-eslint/no-explicit-any

/**
 * How many characters of one value {@link workerActivity} carries before it is
 * clipped ([[BUG-167]]).
 *
 * The whole of `activity` enters the CALLER'S conversation — the expensive one —
 * so it is a pointer at what happened rather than a copy of it. An input or a
 * result long enough to meet this is one the caller can re-read in full from the
 * worker's own session, which `session` on the same result names.
 */
export const ACTIVITY_CLIP = 400

/** The same bound for the worker's last prose, which is the likelier to matter. */
export const LAST_WORDS_CLIP = 800

/** The worker's last tool call, as the host saw it made ([[BUG-167]]). */
export interface WorkerOperation {
  name: string
  /** The arguments, as compact JSON, clipped. Absent when the call carried none. */
  input?: string
  /** What the call returned, clipped — a refusal reads as the refusal. */
  result?: string
}

/**
 * What a worker did, read from its own session log rather than from anything it
 * said ([[BUG-167]]).
 *
 * WHY IT EXISTS. `outcome: silent` means the worker said nothing, and that spans
 * three opposite runs: it did nothing, it did everything, it did some of it and
 * stopped. {@link DraftChanges} already separates the first from the other two on
 * what was WRITTEN. This separates the runs that wrote nothing from each other —
 * a worker that read the page map and stopped, one whose write was refused, and
 * one that made no call at all and reasoned itself into inaction are three
 * different findings, and each is actionable where "silent" is not.
 *
 * THE LOG IS THE MANAGER'S, NOT THE WORKER'S WORD. Every call the worker's
 * backend ran is a `tool` record on its junction, appended by the session
 * manager as the call returned; the worker cannot add to that or edit it. Its
 * prose is there too, and is reported as prose — what it said, not what it did.
 */
export interface WorkerActivity {
  /** How many tool calls the worker made. `0` means it made none at all. */
  operations: number
  /** Absent when {@link operations} is `0`. */
  last_operation?: WorkerOperation
  /** The last thing the worker said, clipped. Absent when it said nothing. */
  last_words?: string
}

/** `text`, or its first `limit` characters and a count of the rest. */
export function clip(text: string, limit: number): string {
  if (text.length <= limit) return text
  return `${text.slice(0, limit)}… [${text.length - limit} more characters]`
}

/**
 * {@link WorkerActivity} from a worker's junction records ([[BUG-167]]).
 *
 * Both readings are the library's own folds — `toolCalls` pairs a call with its
 * result on either backend path, and `applyRecords` is how the transcript view is
 * derived — so there is no second reader of the record format here.
 *
 * The last words are the last assistant turn that SAID something, not simply the
 * last one: a silent worker is asked once more before it is reported silent, and
 * a second turn that said nothing would otherwise hide the first one's prose.
 */
export function workerActivity(lib: Untyped, records: readonly Untyped[]): WorkerActivity {
  const calls = lib.toolCalls(lib.toolRecords(records)) as Untyped[]
  const activity: WorkerActivity = { operations: calls.length }
  const last = calls[calls.length - 1]
  if (last !== undefined) {
    const operation: WorkerOperation = { name: String(last.name ?? '') }
    if (last.hasInput) operation.input = clip(JSON.stringify(last.input ?? null), ACTIVITY_CLIP)
    if (last.hasOutput) {
      const output = typeof last.output === 'string' ? last.output : JSON.stringify(last.output ?? null)
      operation.result = clip(output, ACTIVITY_CLIP)
    }
    activity.last_operation = operation
  }
  const turns = (lib.applyRecords(null, records)?.turns ?? []) as { role?: string; content?: string }[]
  for (let i = turns.length - 1; i >= 0; i -= 1) {
    const words = turns[i].role === 'assistant' ? String(turns[i].content ?? '').trim() : ''
    if (words === '') continue
    activity.last_words = clip(words, LAST_WORDS_CLIP)
    break
  }
  return activity
}

/**
 * Whether a {@link DraftChanges} records anything written ([[BUG-167]]).
 *
 * A truncated list counts: `truncated` is present only when there were more
 * differences than the budget carried, so there were differences.
 */
export function wroteAnything(changed: DraftChanges): boolean {
  return changed.differences.length > 0 || (changed.truncated ?? 0) > 0
}

// ── the surface that carries it ──────────────────────────────────────────────

/**
 * The two result fields this host adds, described where the caller reads the
 * rest of the result ([[BUG-167]]).
 *
 * They are declared rather than merely returned because a field the manual does
 * not mention is one the caller has to guess the meaning of — and `wrote` in
 * particular is only useful if it is read before `summary`.
 */
const HOST_RESULT_FIELDS = {
  wrote:
    "Present whenever 'account' is. True when the host's record shows this delegation " +
    "wrote anything to the site, false when it wrote nothing at all. It is the host's " +
    "fact, not the worker's claim, and it is the first thing to read on a 'silent' " +
    'result: a silent worker that wrote nothing and one that wrote a great deal return ' +
    "the same empty summary, and this is what tells them apart. When it is true, " +
    "'account' says what.",
  activity:
    "Present whenever 'outcome' is not 'reported' — that is, whenever the worker's own " +
    'answer is not a finished report. Read by the host from the worker\'s session log, ' +
    "not from anything the worker said. 'operations' is how many tool calls it made; 0 " +
    "means it reasoned and then did nothing. 'last_operation' is the last call it made — " +
    "its 'name', its 'input' and its 'result' — so a write that was refused shows the " +
    "refusal, and a run that read and then stopped shows the read. 'last_words' is the " +
    'last thing the worker said, when it said anything. Long values are clipped and say ' +
    "so; the worker's own session, named by 'session', holds them in full.",
}

/** `declaration` with {@link HOST_RESULT_FIELDS} added to its result shape. */
function withHostResultFields(declaration: Untyped): Untyped {
  const shapes = declaration.shapes ?? {}
  return {
    ...declaration,
    shapes: { ...shapes, result: { ...(shapes.result ?? {}), ...HOST_RESULT_FIELDS } },
  }
}

/**
 * `DelegationToolbox`, with the host's record attached to every result
 * ([[REQ-340]] behaviour 4), and what the worker did attached to every result
 * the worker did not finish with a report ([[BUG-167]]).
 *
 * WHY IT SUBCLASSES RATHER THAN USING THE FRAMEWORK'S HOOK. BUG-71 landed
 * `DelegationRuntime({ account: { mark, changes } })` for exactly this, and its
 * bracket is the better shape: taken by the framework, so a host cannot supply
 * a record without also supplying the two points a doubting caller checks it
 * against. But both functions are called SYNCHRONOUSLY — `mark(ctx)` and
 * `changes(ctx, from, to)` are used as values, never awaited — and this host's
 * record comes from a `SiteStore`, whose every verb is async because D1 and R2
 * are. A hook that returned a promise would put a promise on the result, which
 * serialises to `{}`: worse for the caller than no field at all.
 *
 * So the bracket is taken here instead, around the public operation, where an
 * await is available. Subclassing IS the framework's extension mechanism —
 * `ToolboxSurface` says to subclass it and define one method per declared
 * operation, and `invoke` resolves the method per call — so this is composition
 * rather than a reach past the API. `account: {from, to, changed}` and its prose
 * are the framework's; `wrote` and `activity` are this host's, and are added to
 * the declaration's result shape so the caller is told about them in the same
 * place it is told about the rest.
 *
 * THE UPSTREAM FIX IS ONE WORD IN TWO PLACES — `await this._mark(ctx)` and
 * `await hook.changes(...)`, which a synchronous hook passes through unchanged.
 * When it lands, the bracket becomes a `runtime.account` pair; `wrote` and
 * `activity` stay here unless upstream grows them too.
 *
 * NOTHING HERE EVER FAILS THE DELEGATION, on upstream's own rule: a capture, a
 * comparison or a log read that throws costs its field and nothing else. A
 * result the caller cannot use because the host's bookkeeping went wrong is a
 * worse trade than a result with one field missing.
 *
 * THE WINDOW IS SLIGHTLY WIDER THAN THE FRAMEWORK'S — it opens before the
 * worker's session is opened rather than just after — and encloses exactly the
 * same work, because opening a session writes nothing to the draft.
 */
export function accountingDelegationToolbox(
  lib: Untyped,
  store: SiteStore,
  site: string,
): Untyped {
  const declaration = withHostResultFields(lib.DelegationToolbox.DECLARATION)
  return class AccountingDelegationToolbox extends lib.DelegationToolbox {
    constructor(runtime: Untyped, options: Untyped = {}) {
      super(runtime, { ...options, decl: options.decl ?? declaration })
    }

    async delegate(input: Untyped): Promise<Untyped> {
      let from: DraftCapture | null = null
      try {
        from = await captureDraft(store, site)
      } catch {
        from = null
      }
      let result = await super.delegate(input)
      if (from !== null) {
        try {
          const to = await captureDraft(store, site)
          const changed = draftChanges(from, to)
          result = { ...result, wrote: wroteAnything(changed), account: { from: from.at, to: to.at, changed } }
        } catch {
          // See above: the record is worth having and never worth losing a result over.
        }
      }
      if (result.outcome === lib.DELEGATION_REPORTED) return result
      try {
        const [records] = this.runtime.manager.logFor(result.session).readFrom(0)
        return { ...result, activity: workerActivity(lib, records) }
      } catch {
        return result
      }
    }
  }
}
