import fs from 'node:fs'
import path from 'node:path'
import { CATALOG } from '@1stcontact/framework/worker'
import { extractStyleBlocks } from '../../../../packages/framework/src/modules/extract-style'

/**
 * Precompiling the behavior modules' chrome (REQ-145).
 *
 * WHY THIS EXISTS. `getModuleCss()` and `getModuleClientJs()` read each module's
 * `index.astro` and `client.js` off disk, *at render time*, for every site — not
 * only for sites that use a module. So the render could not run in workerd at
 * all, which the ticket had not anticipated: the L1 renderer really is portable,
 * but `renderSiteFiles` folds this CSS into every `theme.css` it emits, and a
 * page served without it renders unstyled.
 *
 * Rather than give the Worker a second, thinner render — which is the one thing
 * `render.ts` exists to prevent — the READ moves to build time. The extraction
 * is unchanged and shared (`extract-style.ts`), so the bytes are the bytes the
 * filesystem path produced; only *when* they are read has moved.
 *
 * THE OUTPUT IS COMMITTED, and a UAT re-extracts and compares. A generated file
 * that can go stale silently would serve last week's module CSS with nothing to
 * signal it; a failing test is how that surfaces instead. This is the same
 * bargain the import map takes — derive it, commit it, prove it current.
 *
 * NOTE ON SCOPE. Precompiling the *components* — so a behavior module renders in
 * workerd, not merely paints — is REQ-148. This is only the chrome, which every
 * site needs whether or not it mounts a behavior.
 */

/** Where the module sources live, relative to the repo root. */
const MODULES_DIR = 'packages/framework/src/modules'

/** Where the generated file lands, relative to the repo root. */
const GENERATED = 'packages/framework/src/modules/module-assets.ts'

export interface ModuleAssetBuild {
  /** The generated file's path, relative to the repo root. */
  file: string
  /** Module ids that contributed CSS, in catalog order. */
  css: string[]
  /** Module ids that contributed client behaviour, in catalog order. */
  clientJs: string[]
}

/**
 * The two strings, composed exactly as the filesystem readers composed them.
 *
 * Catalog order, deduplicated by id — `CATALOG` is what `registry` derives its
 * order from, so iterating it here rather than the registry avoids dragging the
 * `.astro` imports into this module while producing the identical sequence.
 */
export function composeModuleAssets(repoRoot: string): {
  css: string
  clientJs: string
  cssIds: string[]
  clientJsIds: string[]
} {
  const dir = path.join(repoRoot, MODULES_DIR)
  const seen = new Set<string>()
  const cssParts: string[] = []
  const jsParts: string[] = []
  const cssIds: string[] = []
  const clientJsIds: string[] = []

  for (const meta of CATALOG) {
    if (seen.has(meta.id)) continue
    seen.add(meta.id)

    const astro = path.join(dir, meta.id, 'index.astro')
    const css = extractStyleBlocks(fs.readFileSync(astro, 'utf8'))
    if (css) {
      cssParts.push(`/* module: ${meta.id} */\n${css}`)
      cssIds.push(meta.id)
    }

    const clientFile = path.join(dir, meta.id, 'client.js')
    if (fs.existsSync(clientFile)) {
      const js = fs.readFileSync(clientFile, 'utf8').trim()
      if (js) {
        jsParts.push(`/* behavior: ${meta.id} */\n${js}`)
        clientJsIds.push(meta.id)
      }
    }
  }

  return { css: cssParts.join('\n\n'), clientJs: jsParts.join('\n\n'), cssIds, clientJsIds }
}

function literal(value: string): string {
  // A template literal would have to escape `${`, and module CSS and client JS
  // are both allowed to contain one. JSON.stringify produces a double-quoted
  // string literal that is valid TypeScript and needs no second escaping rule.
  return JSON.stringify(value)
}

/** Regenerate the committed file. Returns what it contributed. */
export function buildModuleAssets(repoRoot: string): ModuleAssetBuild {
  const { css, clientJs, cssIds, clientJsIds } = composeModuleAssets(repoRoot)
  const source = `// GENERATED by \`1c assets\` (REQ-145). Do not edit.
//
// The behavior modules' static chrome, read from their \`.astro\` and \`client.js\`
// sources at BUILD time so that \`theme.css\` and \`capabilities.js\` can be
// composed in a runtime with no filesystem. See tools/generate/src/cli/module-assets.ts
// for why, and the REQ-145 UAT for the check that this file still matches its
// sources.

/** Every catalogued module's static \`<style>\` content, in catalog order. */
export const MODULE_CSS = ${literal(css)}

/** Every catalogued behavior's \`client.js\`, in catalog order. */
export const MODULE_CLIENT_JS = ${literal(clientJs)}
`
  fs.writeFileSync(path.join(repoRoot, GENERATED), source)
  return { file: GENERATED, css: cssIds, clientJs: clientJsIds }
}
